// miniapp/src/pages/editclassschedule/index.tsx
import React, { useEffect, useState } from 'react'
import { View, Text } from '@tarojs/components'
import './index.scss'
import { getCurrentInstance } from '@tarojs/runtime'
import { useLazyQuery } from '@apollo/client'
import { academicTermQuery } from '@/graphql/query/classschedule.query.graphql'
import { ClassSchedule, Course } from '@/models/models/classSchedule.model'
import { Button } from '@nutui/nutui-react-taro'
import { ArrowLeft, ArrowRight } from '@nutui/icons-react-taro'

class CourseCell {
  couresId: string | null = null;
  start: number | null = null;
  end: number | null = null;
  teacherNames: string | null = null;
  courseName: string | null = null;
  courseType: string | null = null;
  courseLocation: string | null = null;
  courseWeeks: number[] | null = null;
  studentCount: number | null = null;
  color: string | null = null;
}

function Index() {

  const daysOfWeek = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];
  const periods = ['一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '十一', '十二', '十三'];

  const [classScheduleQuery] = useLazyQuery(academicTermQuery)

  const [classSchedule, setClassSchedule] = useState<ClassSchedule | null>(null);
  const [currentWeek, setCurrentWeek] = useState<number>(1);
  const [nowWeek, setNowWeek] = useState<number>(1);
  const [classScheduleMatrix, setClassScheduleMatrix] = useState<CourseCell[][]>(Array(7).fill(null).map(() => Array(periods.length).fill(null)));

  const $instance = getCurrentInstance()

  const getWeekNumber = (startDate: Date): number => {
    let now = new Date();
    let start = new Date(startDate);
    let diffInTime = now.getTime() - start.getTime();
    let diffInDays = Math.floor(diffInTime / (1000 * 3600 * 24));
    let startDay = start.getDay();
    let nowDay = now.getDay();
    let weekNumber = Math.floor(diffInDays / 7);
    if (startDay >= nowDay) weekNumber++;
    return weekNumber;
  }

  useEffect(() => {
    let id = $instance.router?.params.id
    if (id) {
      classScheduleQuery({
        variables: {
          id: id
        }
      }).then((res) => {
        let classSchedule = res.data.academicTerm
        console.log(classSchedule)
        setClassSchedule(classSchedule);
        updateClassScheduleMatrix(classSchedule.courses);
        const week = getWeekNumber(new Date(classSchedule.startDate))
        setNowWeek(week);
        setCurrentWeek(week);
      })
    }
  }, []);

  const updateClassScheduleMatrix = (courses: Course[]) => {
    let matrix: CourseCell[][] = Array(7).fill(null).map(() => Array(periods.length).fill(null));

    for (let course of courses) {
      for (let courseTime of course.courseTimes) {
        let dayOfWeek = courseTime.dayOfWeek;

        let courseCell = new CourseCell();
        courseCell.couresId = course.id;
        courseCell.start = courseTime.start;
        courseCell.end = courseTime.end;
        courseCell.teacherNames = course.teacherNames;
        courseCell.courseName = course.courseName;
        courseCell.courseType = course.courseType;
        courseCell.courseLocation = course.courseLocation;
        courseCell.courseWeeks = course.courseWeeks;
        courseCell.studentCount = course.studentCount;
        courseCell.color = course.color;

        for (let i = courseTime.start - 1; i < courseTime.end; i++) {
          matrix[dayOfWeek - 1][i] = courseCell;
        }
      }
    }

    console.log(matrix)
    setClassScheduleMatrix(matrix);
  }

  return (
    <View className="container">
      {classSchedule &&
        <>
          <View style={{ width: '100%', height: '120rpx', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Button fill="none" style={{ margin: '8' }} disabled={currentWeek == 1} onClick={() => { if (currentWeek > 1) { setCurrentWeek(currentWeek - 1) } }}>
              <ArrowLeft />
            </Button>
            <View style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
              <View>{classSchedule.termName}</View>
              <View>第 {currentWeek} 周</View>
              {nowWeek !== currentWeek && <View>当前为第 {nowWeek} 周</View>}
            </View>
            <Button fill="none" style={{ margin: '8' }} disabled={currentWeek == classSchedule.weekCount} onClick={() => { if (currentWeek < classSchedule.weekCount) { setCurrentWeek(currentWeek + 1) } }}>
              <ArrowRight />
            </Button>
          </View>

          <View style={{ height: '2500rpx', overflow: 'auto' }}>
            <View style={{ height: '100%', display: 'flex', flexDirection: 'row' }}>
              <View style={{ display: 'flex', flexDirection: 'column', flex: '1', borderRight: '1px solid #b7c9e9', borderLeft: '1px solid #b7c9e9' }}>
                <View style={{ flex: '0.5', borderBottom: '1px solid #b7c9e9', borderTop: '1px solid #b7c9e9', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>时间</View>
                {periods.map((period, periodIndex) => {
                  return <View key={periodIndex} style={{ flex: '1', borderBottom: '1px solid #b7c9e9', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>{period}</View>
                })}
              </View>
              {daysOfWeek.map((dayOfWeek, dayOfWeekIndex) => {
                return (
                  <View key={dayOfWeekIndex} style={{ display: 'flex', flexDirection: 'column', flex: '1', borderRight: '1px solid #b7c9e9' }}>
                    <View style={{ flex: '0.5', borderBottom: '1px solid #b7c9e9', borderTop: '1px solid #b7c9e9', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>{dayOfWeek}</View>
                    {periods.map((period, periodIndex) => {
                      let courseCell = classScheduleMatrix[dayOfWeekIndex][periodIndex];
                      if (courseCell === null || courseCell === undefined) {
                        return <View key={periodIndex} style={{ flex: '1', borderBottom: '1px solid #b7c9e9', display: 'flex', justifyContent: 'center', alignItems: 'center' }}></View>
                      }
                      if (courseCell.start === periodIndex + 1 && courseCell.courseWeeks?.includes(currentWeek)) {
                        return (
                          <View key={periodIndex} style={{ flex: courseCell.end! - courseCell.start! + 1, backgroundColor: courseCell.color!, borderBottom: '1px solid #b7c9e9', display: 'flex', justifyContent: 'center', alignItems: 'center', borderRadius: '20rpx', color: 'white' }}>
                            {courseCell &&
                              <View>
                                <View style={{ wordBreak: 'break-all' }}>{courseCell.courseName}</View>
                                <View style={{ wordBreak: 'break-all' }}>{courseCell.courseLocation}</View>
                                <View style={{ wordBreak: 'break-all' }}>{courseCell.teacherNames}</View>
                              </View>
                            }
                          </View>
                        )
                      } else if (!courseCell.courseWeeks?.includes(currentWeek)) {
                        return <View key={periodIndex} style={{ flex: '1', borderBottom: '1px solid #b7c9e9', display: 'flex', justifyContent: 'center', alignItems: 'center' }}></View>
                      }
                    })}
                  </View>
                )
              })}
            </View>
          </View>
        </>
      }
    </View>
  )
}

export default Index

// frontend/src/app/pages/classschedulepage/editclassschedule/editclassschedule.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ClassScheduleService } from '../../../services/classschedule.service';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Subject, takeUntil } from 'rxjs';
import { ClassSchedule, Course, EditClassSchedule } from '../../../models/models/classSchedule.model';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { provideNativeDateAdapter } from '@angular/material/core';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatDividerModule } from '@angular/material/divider';
import { FormArray, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { CoursedialogComponent } from '../../../components/coursedialog/coursedialog.component';

@Component({
  selector: 'app-editclassschedule',
  standalone: true,
  providers: [provideNativeDateAdapter()],
  imports: [MatButtonModule, MatIconModule, MatInputModule, MatFormFieldModule, MatDatepickerModule,
    MatDividerModule, ReactiveFormsModule],
  templateUrl: './editclassschedule.component.html',
  styleUrl: './editclassschedule.component.scss'
})
export class EditclassscheduleComponent implements OnInit, OnDestroy {

  private destory$ = new Subject<boolean>();
  classSchedule: ClassSchedule | null = null;

  daysOfWeek = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];
  periods = ['一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '十一', '十二', '十三'];

  currentWeek = 1;
  nowWeek = 1;

  editDrawer = false;

  classScheduleMatrix: CourseCell[][] = [];

  classScheduleForm!: FormGroup;

  constructor(
    private activatedRoute: ActivatedRoute,
    private classScheduleService: ClassScheduleService,
    private snackBar: MatSnackBar,
    private dialog: MatDialog
  ) { }



  updateClassSchedule(): void {
    if (this.classScheduleForm.invalid) {
      this.snackBar.open('请检查表单', '关闭', {
        duration: 2000,
      });
      return;
    }

    let classSchedule = new EditClassSchedule();
    classSchedule.termName = this.classScheduleForm.get('name')?.value;
    classSchedule.startDate = this.classScheduleForm.get('startDate')?.value;
    classSchedule.weekCount = this.classScheduleForm.get('weekCount')?.value;

    this.classScheduleService.updateClassSchedule(this.classSchedule!.id, classSchedule)
      .pipe(takeUntil(this.destory$)).subscribe({
        next: (result) => {
          if (result) {
            this.classSchedule = result;
            this.classScheduleMatrix = this.convertToMatrix(this.classSchedule);

            this.nowWeek = this.getWeekNumber(this.classSchedule.startDate);
            if (this.nowWeek > this.classSchedule.weekCount) {
              this.currentWeek = this.classSchedule.weekCount;
            } else {
              this.currentWeek = this.nowWeek;
            }

            this.classScheduleForm.patchValue({
              name: this.classSchedule?.termName,
              startDate: this.classSchedule?.startDate,
              weekCount: this.classSchedule?.weekCount
            });

            this.snackBar.open('更新课表成功', '关闭', { duration: 2000 });
          } else {
            this.snackBar.open('更新课表失败', '关闭', {
              duration: 2000,
            });
          }
        },
        error: (error) => {
          console.error(error);
          this.snackBar.open('更新课表失败', '关闭', {
            duration: 2000,
          });
        }
      });

    this.editDrawer = false;
  }

  createCourse(): void {
    const dialogRef = this.dialog.open(CoursedialogComponent, {
      width: '600px',
      height: '500px',
      data: { course: null, buttonLabel: '创建', weekCount: this.classSchedule?.weekCount }
    });
  }

  openEditCourse(course: Course) {

  }

  openEditDrawer(): void {
    this.editDrawer = true
    this.classScheduleForm.patchValue({
      name: this.classSchedule?.termName,
      startDate: this.classSchedule?.startDate,
      weekCount: this.classSchedule?.weekCount
    });
  }

  convertToMatrix(classSchedule: ClassSchedule | null): CourseCell[][] {
    if (!classSchedule) return [];

    let matrix: CourseCell[][] = Array(7).fill(null).map(() => Array(this.periods.length).fill(null));

    for (let course of classSchedule.courses) {
      for (let courseTime of course.courseTimes) {
        let dayOfWeek = courseTime.dayOfWeek
        let courseCell = new CourseCell();
        courseCell.couresId = course.id
        courseCell.start = courseTime.start
        courseCell.end = courseTime.end
        courseCell.teacherNames = course.teacherNames
        courseCell.courseName = course.courseName
        courseCell.courseType = course.courseType
        courseCell.courseLocation = course.courseLocation
        courseCell.studentCount = course.studentCount
        courseCell.color = course.color

        for (let i = courseTime.start - 1; i < courseTime.end; i++) {
          matrix[dayOfWeek][i] = courseCell;
        }
      }
    }

    return matrix;
  }

  getWeekNumber(startDate: Date): number {
    let now = new Date();
    let start = new Date(startDate);
    let diffInTime = now.getTime() - start.getTime();
    let diffInDays = Math.floor(diffInTime / (1000 * 3600 * 24));
    let startDay = start.getDay();
    let nowDay = now.getDay();
    let weekNumber = Math.floor(diffInDays / 7);
    if (startDay >= nowDay) weekNumber++;
    return weekNumber;
  }

  ngOnInit(): void {
    this.activatedRoute.params.pipe(takeUntil(this.destory$)).subscribe(params => {
      this.classScheduleService.getClassSchedule(params['id'])
        .pipe(takeUntil(this.destory$)).subscribe({
          next: (result) => {
            if (result) {
              this.classSchedule = result;
              this.classScheduleMatrix = this.convertToMatrix(this.classSchedule);
              this.nowWeek = this.getWeekNumber(this.classSchedule.startDate);
              if (this.nowWeek > this.classSchedule.weekCount) {
                this.currentWeek = this.classSchedule.weekCount;
              } else {
                this.currentWeek = this.nowWeek;
              }

              this.classScheduleForm = new FormGroup({
                name: new FormControl(this.classSchedule.termName || '', [Validators.required]),
                startDate: new FormControl(this.classSchedule.startDate || null, [Validators.required]),
                weekCount: new FormControl(this.classSchedule.weekCount || 0, [Validators.required]),
              });

              console.log(this.classSchedule);
              this.snackBar.open('获取课表成功', '关闭', { duration: 2000 });
            } else {
              this.snackBar.open('获取课表失败', '关闭', {
                duration: 2000,
              });
            }
          },
          error: (error) => {
            console.error(error);
            this.snackBar.open('获取课表失败', '关闭', {
              duration: 2000,
            });
          }
        });
    });
  }

  ngOnDestroy(): void {
    this.destory$.next(true);
    this.destory$.complete();
  }
}

class CourseCell {
  couresId: string | null = null;
  start: number | null = null;
  end: number | null = null;
  teacherNames: string | null = null;
  courseName: string | null = null;
  courseType: string | null = null;
  courseLocation: string | null = null;
  courseWeeks: number[] | null = null;
  studentCount: number | null = null;
  color: string | null = null;
}

@if(classSchedule)
{
<div class="container">
  <div class="header">
    <div style="display: flex; flex-direction: column; align-items: center;">
      <div style="display: flex; flex-direction: row; gap: 1rem; align-items: center;">
        <button mat-icon-button color="primary" [disabled]="currentWeek<=1" (click)="currentWeek=currentWeek-1">
          <mat-icon>arrow_back</mat-icon>
        </button>
        <div>第 {{currentWeek}} 周</div>
        <button mat-icon-button color="primary" [disabled]="currentWeek>=classSchedule.weekCount"
          (click)="currentWeek=currentWeek+1">
          <mat-icon>arrow_forward</mat-icon>
        </button>
      </div>
      @if(currentWeek!==nowWeek){
      <div>当前第 {{nowWeek}} 周</div>
      }
    </div>
    <div style="font-size:larger;">{{classSchedule.termName}}</div>
    <div>
      <button mat-raised-button color="primary" (click)="openEditDrawer()">编辑</button>
    </div>
  </div>
  <div style="padding: 10px 40px; box-sizing: border-box; width: 100%; height: 100%;">
    <table>
      <thead>
        <tr>
          <th></th>
          @for(day of daysOfWeek;track $index){
          <th>{{day}}</th>
          }
        </tr>
      </thead>
      <tbody>
        @for(period of periods;track periodIndex; let periodIndex= $index){
        <tr>
          @for(day of daysOfWeek;track dayIndex;let dayIndex= $index){
          @if(dayIndex === 0){
          <td>{{period}}</td>
          }
          @if(classScheduleMatrix[dayIndex][periodIndex]!==null&&classScheduleMatrix[dayIndex][periodIndex]!==undefined){
          @if(classScheduleMatrix[dayIndex][periodIndex].start!-1===periodIndex &&
          classScheduleMatrix[dayIndex][periodIndex].courseWeeks!.includes(currentWeek)){
          <td
            [rowSpan]="classScheduleMatrix[dayIndex][periodIndex].end!-classScheduleMatrix[dayIndex][periodIndex].start!+1"
            [style.background-color]="classScheduleMatrix[dayIndex][periodIndex].color">
            <div style="display: flex; flex-direction: column; gap: 5px;">
              <div>{{classScheduleMatrix[dayIndex][periodIndex].courseName}}</div>
              <div>{{classScheduleMatrix[dayIndex][periodIndex].teacherNames}}</div>
              <div>{{classScheduleMatrix[dayIndex][periodIndex].courseType}}</div>
              <div>{{classScheduleMatrix[dayIndex][periodIndex].courseLocation}}</div>
              <div>{{classScheduleMatrix[dayIndex][periodIndex].studentCount}}</div>
            </div>
          </td>
          }
          }@else {
          <td></td>
          }
          }
        </tr>
        }
      </tbody>
    </table>
  </div>
</div>
@if(editDrawer){
<div class="drawer">
  <div class="action">
    <button mat-icon-button (click)="editDrawer=false" color="primary">
      <mat-icon>close</mat-icon>
    </button>
    <button mat-icon-button color="primary" (click)="createCourse()">
      <mat-icon>add</mat-icon>
    </button>
  </div>
  <div class="classScheduleItem" [formGroup]="classScheduleForm">
    <mat-form-field appearance="outline">
      <mat-label>课程表名称</mat-label>
      <input matInput placeholder="课程表名称" formControlName="name">
      <mat-error>课程表名称不能为空</mat-error>
    </mat-form-field>
    <mat-form-field appearance="outline">
      <mat-label>开始日期</mat-label>
      <input matInput [matDatepicker]="picker" formControlName="startDate" placeholder="开始日期">
      <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
      <mat-datepicker #picker></mat-datepicker>
      <mat-error>开始日期不能为空</mat-error>
    </mat-form-field>
    <mat-form-field appearance="outline">
      <mat-label>学期周数</mat-label>
      <input matInput type="number" formControlName="weekCount" placeholder="学期周数">
      <mat-error>周数不能为空</mat-error>
    </mat-form-field>
    <button mat-raised-button color="primary" [disabled]="classScheduleForm.invalid" (click)="updateClassSchedule()">
      更新
    </button>
  </div>

  <div class="courseList">
    @for(course of classSchedule.courses;track $index){
    <div class="courseItem" (click)="openEditCourse(course)">
      <div>{{course.courseName}}</div>
      <div>{{course.teacherNames}}</div>
    </div>
    }@empty {
    <div>暂无课程</div>
    }
  </div>
</div>
}
}
